name: Scheduled Netlify deploy

on:
  schedule:
    - cron: "17 6 * * MON,WED,SAT"

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Trigger hook
        run: curl -d '' https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_HOOK_ID }}
